# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deploy

permissions:
  contents: read


on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  workflow_dispatch:


jobs:
  prepare-1:
    if: true
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      - name: Deploy
        run: echo "deploy"

  prepare-2:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      - name: Deploy
        # run: echo "deploy"
        run: exit 127
  aaa-deploy:
    name: "Deploy ${{ inputs.environment }}"
    needs:
      - prepare-1
      - prepare-2
    # ifの条件によりskipされたjobは無視するためにcontainsでフィルタする
    if: |
      always()
        && ( !contains(needs.*.result, 'succeeded') || !contains(needs.*.result, 'skipped') )

    # if: |
    #     !contains(needs.*.result, 'failure')
    runs-on: ubuntu-latest
    environment: "${{ inputs.environment }}"
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      - name: Deploy
        run: echo "deploy"

  prepare-3:
    if: true
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      - name: Deploy
        run: echo "deploy"
